services:
  wsproxy:
    image: jwnmulder/websockify:0.12
    container_name: wsproxy
    platform: linux/amd64
    ports:
      - "127.0.0.1:3003:80" 
    command: "80 --token-plugin JSONTokenApi --token-source 'http://wsproxy-test-client:3010/?token=%s'"
